# Generated by Django 5.2.4 on 2025-08-08 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("image_app", "0003_add_document_page_fields"),
    ]

    operations = [
        migrations.RenameField(
            model_name="document",
            old_name="filepath",
            new_name="file_path",
        ),
    ]
