# Generated by Django 5.2.4 on 2025-10-06 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_app', '0004_rename_filepath_document_file_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='html_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
